name: CathayAnchor
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36142
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050708'
    - '#f9fbf7'
    - '#102040'
    - '#304e64'
    - '#bdcfca'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
