name: CathayAnchor
favicon: null
layout_spectrum: 0
typography_spectrum: 0.36142
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050708'
    - '#f9fbf7'
    - '#102040'
    - '#304e64'
    - '#bdcfca'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
